features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  logo: true
  name: true
  node_user_picture: 1
  slogan: true
facebook_url: 'https://www.facebook.com/zymphonies'
twitter_url: 'https://twitter.com/zymphonies'
google_plus_url: 'https://plus.google.com/+ZymphoniesTechnologies'
linkedin_url: 'https://www.linkedin.com/in/durdina-milovic-1aa565114/'
pinterest_url: 'https://www.pinterest.com/zymphonies'
rss_url: rss.xml
copyright_text: 'Copyright 2015· All rights reserved'
show_social_icon: 1
show_credit_link: 1
_core:
  default_config_hash: FIKpUAUBhRvu30trYoPz9z7O8dAeWlZ3GILxKamftng
logo:
  use_default: 0
  path: 'public://Milovic_Djurdjina_web_0.jpg'
favicon:
  use_default: 1
